//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LPMsg.proto
namespace LPMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GUID")]
  public partial class GUID : global::ProtoBuf.IExtensible
  {
    public GUID() {}
    
    private byte[] _head;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"head", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] head
    {
      get { return _head; }
      set { _head = value; }
    }
    private byte[] _data;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqRegister")]
  public partial class ReqRegister : global::ProtoBuf.IExtensible
  {
    public ReqRegister() {}
    
    private int _server_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"server_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int server_id
    {
      get { return _server_id; }
      set { _server_id = value; }
    }
    private string _server_name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"server_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string server_name
    {
      get { return _server_name; }
      set { _server_name = value; }
    }
    private string _message;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AckRegister")]
  public partial class AckRegister : global::ProtoBuf.IExtensible
  {
    public AckRegister() {}
    
    private int _server_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"server_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int server_id
    {
      get { return _server_id; }
      set { _server_id = value; }
    }
    private string _server_name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"server_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string server_name
    {
      get { return _server_name; }
      set { _server_name = value; }
    }
    private string _message;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TestString")]
  public partial class TestString : global::ProtoBuf.IExtensible
  {
    public TestString() {}
    
    private string _str_value1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"str_value1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string str_value1
    {
      get { return _str_value1; }
      set { _str_value1 = value; }
    }
    private int _num_value1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"num_value1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num_value1
    {
      get { return _num_value1; }
      set { _num_value1 = value; }
    }
    private int _num_value2;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"num_value2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num_value2
    {
      get { return _num_value2; }
      set { _num_value2 = value; }
    }
    private int _num_value3;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"num_value3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num_value3
    {
      get { return _num_value3; }
      set { _num_value3 = value; }
    }
    private string _str_value2;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"str_value2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string str_value2
    {
      get { return _str_value2; }
      set { _str_value2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqLogin")]
  public partial class ReqLogin : global::ProtoBuf.IExtensible
  {
    public ReqLogin() {}
    
    private string _account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AckLogin")]
  public partial class AckLogin : global::ProtoBuf.IExtensible
  {
    public AckLogin() {}
    
    private string _account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private int _error_code;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private string _message;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}